### ISSUE TITLE
Azure IDs are giving out too much information

### ISSUE THREAD

**Issue by sergiuser1** [IonSeremet/Licenta_Back_End#1]
In the GitHub workflow you have
```
with:
  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BAE2FF4409134FBD8055C928E716552F }}
  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C60E79DA3EAF43B68E0EDBF8BCE07AB0 }}
  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_791B6E7AB3864D53BB12DE29879C473A }}
  ```
  The secrets name should be changed
